[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # Increase timeout for AI operations
  [functions.api]
    timeout = 120
  [functions.game-title]
    timeout = 120
  [functions.game-info]
    timeout = 120
  [functions.chat]
    timeout = 120
  [functions.predict-genre]
    timeout = 120
  [functions.article-info]
    timeout = 120
  [functions.igdb-search]
    timeout = 60

# Redirect specific API endpoints to dedicated functions - handle both relative and absolute URLs
[[redirects]]
  from = "/api/game-title"
  to = "/.netlify/functions/game-title"
  status = 200
  force = true

[[redirects]]
  from = "/api/game-info"
  to = "/.netlify/functions/game-info"
  status = 200
  force = true

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
  force = true

[[redirects]]
  from = "/api/predict-genre"
  to = "/.netlify/functions/predict-genre"
  status = 200
  force = true

[[redirects]]
  from = "/api/article-info"
  to = "/.netlify/functions/article-info"
  status = 200
  force = true

[[redirects]]
  from = "/api/igdb/search"
  to = "/.netlify/functions/igdb-search"
  status = 200
  force = true

# Handle the absolute URL versions as shown in the minified code
[[redirects]]
  from = "https://sophsgamereviews.netlify.app/api/game-title"
  to = "/.netlify/functions/game-title"
  status = 200
  force = true

[[redirects]]
  from = "https://sophsgamereviews.netlify.app/api/game-info"
  to = "/.netlify/functions/game-info"
  status = 200
  force = true

[[redirects]]
  from = "https://sophsgamereviews.netlify.app/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
  force = true

[[redirects]]
  from = "https://sophsgamereviews.netlify.app/api/predict-genre"
  to = "/.netlify/functions/predict-genre"
  status = 200
  force = true

[[redirects]]
  from = "https://sophsgamereviews.netlify.app/api/article-info"
  to = "/.netlify/functions/article-info"
  status = 200
  force = true

[[redirects]]
  from = "https://sophsgamereviews.netlify.app/api/igdb/search"
  to = "/.netlify/functions/igdb-search"
  status = 200
  force = true

# API catch-all routes to the general api function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle client-side routing for all non-API routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 