[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # Increase timeout for AI operations
  [functions.api]
    timeout = 30
  [functions.game-title]
    timeout = 30

# Redirect specific API endpoints to dedicated functions - handle both relative and absolute URLs
[[redirects]]
  from = "/api/game-title"
  to = "/.netlify/functions/game-title"
  status = 200
  force = true

# Handle the absolute URL version as shown in the minified code
[[redirects]]
  from = "https://sophsgamereviews.netlify.app/api/game-title"
  to = "/.netlify/functions/game-title"
  status = 200
  force = true

# API catch-all routes to the general api function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle client-side routing for all non-API routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 