[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # Increase timeout for AI operations
  [functions.api]
    timeout = 30

# API routes should point to our api function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle client-side routing for all non-API routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 